package(default_visibility = [
    "//proj-1/cluster-a/stage:__subpackages__",
    "//proj-2/cluster-b/prod:__subpackages__",
    "//proj-3/cluster-c/prod:__subpackages__",
])

filegroup(
    name = "echoapp",
    srcs = [
        "echo.pod.yaml",
        "kustomization.yaml",
    ],
)
